// (isoCode, displayName)  — empty isoCode means auto-detect
const kTranscriptionLanguages = <(String, String)>[
  ('', 'Auto'),
  ('en', 'English'),
  ('ru', 'Русский'),
  ('uk', 'Українська'),
  ('de', 'Deutsch'),
  ('fr', 'Français'),
  ('es', 'Español'),
  ('it', 'Italiano'),
  ('pt', 'Português'),
  ('pl', 'Polski'),
  ('nl', 'Nederlands'),
  ('sv', 'Svenska'),
  ('no', 'Norsk'),
  ('da', 'Dansk'),
  ('fi', 'Suomi'),
  ('cs', 'Čeština'),
  ('ro', 'Română'),
  ('hu', 'Magyar'),
  ('tr', 'Türkçe'),
  ('ar', 'العربية'),
  ('zh', '中文'),
  ('ja', '日本語'),
  ('ko', '한국어'),
  ('hi', 'हिन्दी'),
  ('id', 'Bahasa Indonesia'),
  ('vi', 'Tiếng Việt'),
  ('th', 'ภาษาไทย'),
  ('el', 'Ελληνικά'),
];
